name: Nucamp Tutorials App Pipeline

# set up how the workflow is triggered

on:

  # Trigger the workflow on push or pull request events on the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # allow triggering this workflow manually from the actions tab
  workflow_dispatch:

# setup th ejob for this workflow
jobs:
  # this workflowcontaines a single job that we are calling "bubilt-and-test"
  build-and-test:

    # the runner env to use
    runs-on: ubuntu-latest

    # steps mostly contain cli commands (via 'run') and actions (via 'uses')
    # each step begins with a hyphen -
    steps:
      # checks out your rep under #GITHUB_WORKSPACE, so your job can access it
      # you can optionally provide a name before a step.  This is an example of an unnamed step.
      - uses: actions/checkout@v2

      # runs a single echo command using the runners shell
      - run: echo Entering Django CI/CD Pipeline!

      # uses the action setup-python@v2, spec version 3.9
      # this installs python 3.9 to the runner env
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-verson: 3.9
      # runs a set of commands to install dependencies in the runner env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # runs database migrations on the django app
      - name: run migrations
        run: python manage.py migrate

      # run all tests with verbose flag
      - name: run all tests
        run: pytest -v
        
    
